Fixing issue #68 by generating a centerline NIFTI file for subjects who do not have a SC mask NIFTI file
neuropoly/template pull request #69
Opened 2023-08-08 13:51 UTC by NadiaBlostein

Fixing issue #68: In `preprocess_normalize.py`, the `straighten_all_subjects()` method requires for each subject to either have a SC mask NIFTI file (`*_label-SC_mask.nii.gz`) or a centerline NIFTI file (`*_label-centerline.nii.gz`). The current PR allows for `preprocess_normalize.py` to generate a centerline NIFTI file for each subject that has neither a SC mask NIFTI file nor a centerline NIFTI file.

Fixes #70

2023-08-08 15:52 UTC, NadiaBlostein commented
> title + body of the PR should be "human readable" as i said multiple times in the past-- @rohanbanerjee will review/modify first, then I review

Is this better?

2023-08-08 16:45 UTC, rohanbanerjee requested changes
I have tested this only my dog data for a subject where there was no centerline file or segmentation file and the PR creates a centerline file where there is not centerline or segmentation ✅ 

However, before this is merged, I would like to understand as to why this change is required. From the documentation, having the segmentation for the subject(s) (step `1.3`) is a requirement to run the `preprocess_normalize.py` (step `1.6`). So technically a user should not be running `1.6` if the `1.3` isn't completed. Please let me know if I am missing out on something here.

2023-08-08 16:59 UTC, jcohenadad reviewed
If a centerline is a possible input in the derivatives, then it should maybe also be listed here:
https://github.com/neuropoly/template/blob/da4d99499b80d1b02b735880ae94fa5b3c2c289f/preprocess_normalize.py#L24

as well as in the README

2023-08-08 17:29 UTC, NadiaBlostein commented
@jcohenadad will do tomorrow am

@rohanbanerjee If you read [this](https://github.com/neuropoly/template/blob/5f511c763d72405a6ed21f5fd31979b7a4dd5dcb/preprocess_normalize.py#L473C1-L491C44) part of the code, the straightening should not work if there is no SC mask NIFTI file or centerline NIFTI file to read in. Am I missing something? 

Cheers

2023-08-08 17:39 UTC, jcohenadad commented
> @jcohenadad will do tomorrow am

in the interest of time, @rohanbanerjee can you please do it now so we can merge

2023-08-08 18:42 UTC, rohanbanerjee commented
@NadiaBlostein Yes indeed, the `straighten_all_subjects()` method would not work if there is not SC mask or centerline file. But the point that I made was that no user should run the `preprocess_normalize.py` until they have confirmed that there is a SC/centerline present for each and every subject they have -- which is step `1.3`. They should run step `1.6` which is running the `preprocess_normalize.py` after `1.3` and also possibly after `qc` (step `1.4`)

2023-08-09 14:39 UTC, jcohenadad commented
Testing this PR with the dog data.
Data: `duke/temp/rohan/bids_data`
Code: 16fa7569dd37a0fa54b4f3a35be3d7e7cc187205
config file: 
```json
{
	"path_data": "PATH_TO_BIDS_DATA",
	"include-list": "sub-HarshmanDobby",
	"data_type": "anat",
	"contrast": "t2",
	"suffix_image": "_T2",
	"first_disc": "1",
	"last_disc": "26"
}
```

2023-08-14 18:43 UTC, rohanbanerjee commented
Hello @NadiaBlostein, did you decide about this PR? Could you please go ahead with either closing it or merging it. I am waiting on this PR for a few other PRs that I would like to open.

2023-08-14 21:55 UTC, NadiaBlostein commented
Hey! I'm working on my other lab project this week and moving out of the country. Aren't other people now working on this?

2023-08-14 22:08 UTC, NadiaBlostein commented
@rohanbanerjee I'll just merge this one because all the issues with it that were mentioned in the last meeting have been opened as separate issues

2023-08-14 22:08 UTC, merged